fixed syle issue

diff --git a/bin/set-brightness b/bin/set-brightness
--- a/bin/set-brightness
+++ b/bin/set-brightness
@@ -46,8 +46,8 @@ get_max_brightness() {
 is_brightness_allowed() {
       case $1 in
          ''|*[!0-9]*)
-		echo "$PROGRAM_NAME: error: invalid level, must be an integer."
-		exit 1
+		   echo "$PROGRAM_NAME: error: invalid level, must be an integer."
+		   exit 1
       ;;
       esac
 
@@ -59,12 +59,12 @@ is_brightness_allowed() {
 
 set_brightness() {
    if command -v sudo &> /dev/null; then
-      sudo="sudo"
+         sudo="sudo"
    fi
 
 	brightness=$(echo "$(get_max_brightness) * $1/100" | bc)
-	echo "$brightness" | $sudo tee $SET_BRIGHTNESS_PATH > /dev/null
-	echo "🔆 Brightness Level: ${1}%" 
+   echo "$brightness" | $sudo tee $SET_BRIGHTNESS_PATH > /dev/null
+   echo "🔆 Brightness Level: ${1}%" 
 }
 
 parse_cli "$1"
